# Generated by Django 2.1 on 2019-08-22 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoAlternativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativas', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterios', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Decisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('avaliou_criterios', models.BooleanField(default=False, null=True)),
                ('avaliou_alternativas', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('decisores', models.ManyToManyField(related_name='_projeto_decisores_+', to='core.Decisor')),
            ],
        ),
        migrations.AddField(
            model_name='decisor',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
        migrations.AddField(
            model_name='criterio',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
        migrations.AddField(
            model_name='avaliacaocriterios',
            name='decisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Decisor'),
        ),
        migrations.AddField(
            model_name='avaliacaocriterios',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
        migrations.AddField(
            model_name='avaliacaoalternativas',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Criterio'),
        ),
        migrations.AddField(
            model_name='avaliacaoalternativas',
            name='decisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Decisor'),
        ),
        migrations.AddField(
            model_name='avaliacaoalternativas',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
        migrations.AddField(
            model_name='alternativa',
            name='projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Projeto'),
        ),
    ]
