# Generated by Django 2.1 on 2018-11-19 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvaliacaoAlternativa',
            new_name='AvaliacaoAlternativas',
        ),
    ]
