# Generated by Django 2.1 on 2018-11-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisor',
            name='avaliou_alternativas',
            field=models.BooleanField(default=False),
        ),
    ]
